
export type NavigationTab = 'home' | 'free' | 'vip' | 'guide' | 'profile' | 'admin' | 'kelly' | 'concierge' | 'stats' | 'results' | 'live' | 'tables';

export type Language = 'en' | 'fr';

export type Sport = 'football' | 'basketball';

export interface Match {
  id: string;
  league: string;
  leagueId?: number;
  seasonId?: number;
  fixtureId?: number;
  homeTeam: string;
  homeTeamId?: number;
  awayTeam: string;
  awayTeamId?: number;
  time: string;
  prediction: string; // Fallback
  prediction_en?: string;
  prediction_fr?: string;
  confidence: number;
  odds: number;
  category: 'safe' | 'value' | 'risky' | 'lean' | 'no_edge';
  analysis?: string; // Fallback
  analysis_en?: string;
  analysis_fr?: string;
  isLive?: boolean;
  homeTeamLogo?: string;
  awayTeamLogo?: string;
  sport?: Sport;
  // Grading Fields
  status?: 'won' | 'lost' | 'void' | 'pending';
  score?: string; // e.g. "2-1"
  graded_at?: string;
  graded_by?: 'live_auto' | 'grading_engine' | 'chatgpt' | 'admin';
  live_state?: string; // e.g. "1H", "2H", "FT", "NS"
  live_minute?: number; // e.g. 45, 67, 90
  // Match Details / AI Generated Stats
  homeForm?: string;
  awayForm?: string;
  homeWinRate?: number;
  awayWinRate?: number;
  homeAvgScored?: number;
  awayAvgScored?: number;
  homeAvgConceded?: number;
  awayAvgConceded?: number;
  homeCleanSheetRate?: number;
  awayCleanSheetRate?: number;
  h2hHomeWins?: number;
  h2hAwayWins?: number;
  h2hDraws?: number;
  h2hLast5Goals?: string;
  homeInjured?: string[];
  awayInjured?: string[];
  // ── Quant Engine Fields ──────────────────────────────────────────────────────
  // Set when predictions are generated by the statistical model pipeline
  expected_value?: number;       // e.g. 0.17 (= 17% EV)
  ev_pct?: number;               // same as above * 100, for display
  kelly_stake?: number;          // % of bankroll to stake (e.g. 2.5)
  market_prob?: number;          // bookmaker implied probability
  market_implied_prob?: number;  // alias
  inefficiency?: number;         // model_prob - market_prob
  bet_type?: string;             // e.g. "Home Win", "Over 2.5 Goals", "BTTS"
  expected_goals_home?: number;  // xG home
  expected_goals_away?: number;  // xG away
  model?: 'quant' | 'ai';       // source of prediction
  model_confidence?: number;     // 0–1 model agreement score
  home_win_prob?: number;        // all market probs from quant model
  draw_prob?: number;
  away_win_prob?: number;
  over25_prob?: number;
  under25_prob?: number;
  over15_prob?: number;
  over35_prob?: number;
  btts_prob?: number;
  double_chance_1x?: number;
  double_chance_x2?: number;
  all_value_bets?: Array<{ market: string; prob: number; odds: number; ev: number }>;
  // ── Match Analysis Platform fields (snake_case from pipeline) ────────────────
  value_rank?: 'high' | 'medium' | 'low' | 'none';
  league_tier?: number;
  home_form?: string;
  away_form?: string;
  home_win_rate?: number;
  away_win_rate?: number;
  home_avg_scored?: number;
  away_avg_scored?: number;
  home_avg_conceded?: number;
  away_avg_conceded?: number;
  home_clean_sheet_rate?: number;
  away_clean_sheet_rate?: number;
  home_xg_avg?: number;
  away_xg_avg?: number;
  home_possession?: number;
  away_possession?: number;
  home_shots_on_target?: number;
  away_shots_on_target?: number;
  h2h_home_wins?: number;
  h2h_away_wins?: number;
  h2h_draws?: number;
  // ── Quant snake_case aliases (Python quant pipeline output) ──────────────────
  fixture_id?: number | string;    // same as fixtureId
  kickoff_local?: string;          // local kickoff time string
  probability?: number;            // raw 0–1 model probability
  home_team?: string;              // alias for homeTeam
  away_team?: string;              // alias for awayTeam
  home_team_logo?: string;         // alias for homeTeamLogo
  away_team_logo?: string;         // alias for awayTeamLogo
}


// ── Live Match (from SportMonks /livescores — stored in Firestore live_scores/{date}/matches) ────
export interface LiveEvent {
  id: number;
  type: string;               // 'goal' | 'own_goal' | 'penalty' | 'yellow_card' | 'red_card' | 'substitution' | 'var' | 'event'
  name: string;
  playerName?: string;        // scorer / carded player / player coming on
  playerNameOut?: string;     // player going off (substitutions only)
  minute: number;
  extraMinute?: number;       // stoppage time (e.g. 90+3)
  teamId?: number;
  isHome?: boolean;           // true = home team event
  result?: string;            // score at time of event e.g. "1-0"
}

export interface LiveMatch {
  id: string;             // fixture ID (string)
  homeTeam: string;
  awayTeam: string;
  homeTeamLogo?: string;
  awayTeamLogo?: string;
  homeTeamId?: number;
  awayTeamId?: number;
  homeScore: number;
  awayScore: number;
  league: string;
  leagueId?: number;
  stateShort: string;     // e.g. '1H', 'HT', '2H', 'FT'
  stateLong: string;      // e.g. 'First Half', 'Half Time'
  minute: number;         // elapsed minutes
  events: LiveEvent[];
  updatedAt?: string;
}

// ── Pre-Match News (from SportMonks /news/pre-match — stored in Firestore match_news/{date}) ────
export interface MatchNews {
  id: number;
  fixtureId: number;
  leagueId?: number;
  title: string;
  body?: string;          // Full preview/analysis text (if available)
  type: string;           // e.g. 'preview', 'injury'
}

// ── Match Statistics (from SportMonks ?include=statistics — stored in Firestore match_stats/{date}) ─
export interface StatValue {
  home: number | null;
  away: number | null;
}
export interface MatchStats {
  possession?: StatValue;       // ball possession %
  shots?: StatValue;            // total shots
  shots_on_target?: StatValue;  // shots on target
  corners?: StatValue;          // corner kicks
  fouls?: StatValue;            // fouls committed
  yellow_cards?: StatValue;     // yellow cards
  offsides?: StatValue;         // offsides
}
export interface MatchStatsData {
  fixtureId: number;
  homeTeam: string;
  awayTeam: string;
  stats: MatchStats;
}

export interface AccumulatorLeg {
  fixture_id: string;
  home_team: string;
  away_team: string;
  market: string;
  odds: number;
  model_prob: number;
  expected_value: number;
  league: string;
}

export interface AccumulatorTicket {
  tier: string;
  tier_label: string;
  tier_description: string;
  tier_icon: string;
  leg_count: number;
  combined_odds: number;
  combined_prob: number;
  combined_ev: number;
  kelly_stake: number;
  kelly_stake_unit: string;
  legs: AccumulatorLeg[];
}

export interface AccumulatorSet {
  baseline?: AccumulatorTicket[];
  alpha_edge?: AccumulatorTicket[];
  syndicate?: AccumulatorTicket[];
  variance_play?: AccumulatorTicket[];
}

export interface UserStats {
  balance: number;
  totalWon: number;
  winRate: number;
  membership: 'Free' | 'VIP';
}

export interface UserProfile {
  uid: string;
  email: string;
  displayName?: string;
  isVip: boolean;
  isAdmin?: boolean;
  isBlocked?: boolean;
  country?: string;
  vipExpiry?: string;
  vipPlan?: 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'annual';
  totalPaid?: number;
  createdAt?: string;
  // Referral System
  referralCode?: string;
  referredBy?: string; // UID of the referrer
  referralCount?: number;
  referralEarnings?: number; // Current Available Balance
  lifetimeEarnings?: number; // Total accumulated over time
}

export interface PayoutRequest {
  id: string;
  userId: string;
  userEmail: string;
  amount: number;
  status: 'pending' | 'paid' | 'rejected';
  date: string;
  phoneNumber: string; // MOMO/OM number
  paymentMethod: string;
}

export interface BettingHistoryItem {
  id: string;
  match: string;
  prediction: string;
  status: 'won' | 'lost' | 'pending';
  amount: number;
  date: string;
}

export interface DailyAnalysis {
  date: string;
  matches: Match[];
  rawFixtures?: Match[];
  accumulators?: AccumulatorSet;
  generatedAt?: string;
}

export interface TeamAsset {
  id: string; // Normalized ID (lowercase)
  name: string; // Display Name
  logoUrl: string;
}

export interface WinRateStats {
  daily: number;
  weekly: number;
  monthly: number;
  streak: number;       // consecutive win streak
  todayWon: number;
  todayTotal: number;
}

export interface SavedPick {
  id: string;
  homeTeam: string;
  awayTeam: string;
  prediction: string;
  confidence: number;
  odds: number;
  league: string;
  homeTeamLogo?: string;
  awayTeamLogo?: string;
  sport?: Sport;
  savedAt: string;
}

export type ToastType = 'success' | 'error' | 'info' | 'warning';

export interface Toast {
  id: string;
  message: string;
  type: ToastType;
}