import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Calendar, ChevronRight, Loader2, BookOpen, Zap } from 'lucide-react';
import { getRecentBlogPosts } from '../services/blogService';
import { useAppContext } from '../context/AppContext';

type PostMeta = {
    date: string;
    title: string;
    excerpt: string;
    tags?: string[];
    generatedAt: string;
};

export const BlogIndex: React.FC = () => {
    const { language } = useAppContext();
    const [posts, setPosts] = useState<PostMeta[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        document.title = language === 'fr'
            ? 'Blog Pronostics IA | Vantage AI Cameroun'
            : 'AI Predictions Blog | Vantage AI';

        getRecentBlogPosts(30).then(data => {
            setPosts(data);
            setLoading(false);
        });

        return () => {
            document.title = 'Vantage AI Cameroun - Pronostics Foot 1xBet & Premier Bet (IA)';
        };
    }, [language]);

    const today = new Date().toISOString().split('T')[0];

    return (
        <div className="min-h-screen bg-vantage-bg text-white pb-24">
            {/* Header */}
            <div className="px-4 pt-8 pb-6 max-w-2xl mx-auto">
                <div className="flex items-center gap-3 mb-2">
                    <div className="w-9 h-9 rounded-xl bg-vantage-cyan/10 border border-vantage-cyan/20 flex items-center justify-center">
                        <BookOpen size={18} className="text-vantage-cyan" />
                    </div>
                    <h1 className="text-2xl font-orbitron font-bold">
                        {language === 'fr' ? 'Analyses IA du Jour' : 'AI Match Analyses'}
                    </h1>
                </div>
                <p className="text-sm text-gray-500 ml-12">
                    {language === 'fr'
                        ? 'Articles générés quotidiennement par notre moteur d\'IA pour chaque journée de matchs.'
                        : 'Daily articles generated by our AI engine for every match day.'}
                </p>
            </div>

            <div className="max-w-2xl mx-auto px-4 space-y-3">
                {loading ? (
                    <div className="flex items-center justify-center py-20">
                        <Loader2 size={28} className="text-vantage-cyan animate-spin" />
                    </div>
                ) : posts.length === 0 ? (
                    <div className="text-center py-20 text-gray-500">
                        <BookOpen size={40} className="mx-auto mb-4 text-gray-600" />
                        <p className="font-medium">
                            {language === 'fr' ? 'Aucun article disponible pour le moment.' : 'No posts available yet.'}
                        </p>
                        <p className="text-xs mt-2 text-gray-600">
                            {language === 'fr' ? 'Les articles apparaissent après la génération quotidienne.' : 'Posts appear after daily AI generation.'}
                        </p>
                    </div>
                ) : (
                    posts.map((post, i) => {
                        const isToday = post.date === today;
                        return (
                            <motion.div
                                key={post.date}
                                initial={{ opacity: 0, y: 12 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ delay: i * 0.04, duration: 0.25 }}
                            >
                                <Link
                                    to={`/blog/${post.date}`}
                                    className={`flex items-start gap-4 p-4 rounded-2xl border transition-all hover:bg-white/5 active:scale-[0.99] group
                    ${isToday
                                            ? 'bg-vantage-cyan/5 border-vantage-cyan/20'
                                            : 'bg-white/[0.03] border-white/5'}`}
                                >
                                    {/* Date badge */}
                                    <div className={`shrink-0 w-12 h-12 rounded-xl flex flex-col items-center justify-center text-center
                    ${isToday ? 'bg-vantage-cyan text-black' : 'bg-white/5 text-gray-400'}`}>
                                        <span className="text-[10px] font-bold uppercase leading-none">
                                            {new Date(post.date + 'T12:00:00').toLocaleString(language === 'fr' ? 'fr-FR' : 'en-US', { month: 'short' })}
                                        </span>
                                        <span className="text-xl font-bold leading-none mt-0.5">
                                            {new Date(post.date + 'T12:00:00').getDate()}
                                        </span>
                                    </div>

                                    {/* Content */}
                                    <div className="flex-1 min-w-0">
                                        <div className="flex items-center gap-2 mb-1">
                                            {isToday && (
                                                <span className="flex items-center gap-1 text-[9px] font-bold uppercase tracking-wider text-black bg-vantage-cyan px-1.5 py-0.5 rounded-full">
                                                    <Zap size={8} className="fill-black" />
                                                    {language === 'fr' ? 'Aujourd\'hui' : 'Today'}
                                                </span>
                                            )}
                                        </div>
                                        <h2 className="text-sm font-bold text-white line-clamp-2 leading-snug group-hover:text-vantage-cyan transition-colors">
                                            {post.title || `${language === 'fr' ? 'Pronostics du' : 'Predictions for'} ${post.date}`}
                                        </h2>
                                        {post.excerpt && (
                                            <p className="text-xs text-gray-500 line-clamp-2 mt-1 leading-relaxed">
                                                {post.excerpt}
                                            </p>
                                        )}
                                        {post.tags && post.tags.length > 0 && (
                                            <div className="flex gap-1.5 mt-2 flex-wrap">
                                                {post.tags.slice(0, 3).map(t => (
                                                    <span key={t} className="text-[9px] font-bold uppercase tracking-wider bg-white/5 text-gray-500 px-2 py-0.5 rounded-full">
                                                        {t}
                                                    </span>
                                                ))}
                                            </div>
                                        )}
                                    </div>

                                    <ChevronRight size={18} className="text-gray-600 group-hover:text-vantage-cyan transition-colors shrink-0 mt-1" />
                                </Link>
                            </motion.div>
                        );
                    })
                )}
            </div>
        </div>
    );
};
